version: '2.4'
services:

    obu1:
        hostname: obu1
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:11
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.11
        sysctls:      
            kernel.msgmax:  16384
            
    obu2:
        hostname: obu2
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:12
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.12
        sysctls:      
            kernel.msgmax:  16384
  
    obu3:
        hostname: obu3
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:13
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.13
        sysctls:      
            kernel.msgmax:  16384
            
    obu4:
        hostname: obu4
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:14
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.14
        sysctls:      
            kernel.msgmax:  16384
            
    obu5:
        hostname: obu5
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=5
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:15
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.15
        sysctls:      
            kernel.msgmax:  16384
            
    obu6:
        hostname: obu6
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=6
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:16
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.16
        sysctls:      
            kernel.msgmax:  16384           
            
networks:
  vanetzalan0:
    external: true
    name: vanetzalan0
